/**
 * POST /api/v1/events — ingestion endpoint for client apps.
 *
 * The client's own application (which integrates Resend directly) pushes
 * email events here so EmailOqui can display them in the Owner dashboard.
 *
 * Auth: Bearer token (API key generated by the Developer in EmailOqui).
 * Body: { events: [{ event_id, email, type, campaign_name?, occurred_at? }] }
 *
 * Idempotent: each (workspace_id, event_id) pair is unique — duplicate
 * pushes are silently deduplicated. Returns counts of received + duplicates.
 *
 * The technical provider (Resend) is never named in the API or UI —
 * the endpoint is generic and works with any email provider's events.
 */
import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { createHash } from 'crypto'

const VALID_EVENT_TYPES = new Set([
  'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCE', 'FAILED', 'UNSUBSCRIBE', 'COMPLAINT',
])

interface IncomingEvent {
  event_id: string
  email: string
  type: string
  campaign_name?: string
  campaign_id?: string
  recipient_hash?: string
  occurred_at?: string // ISO date — defaults to now()
}

export async function POST(req: NextRequest) {
  // 1. Authenticate via Bearer token
  const auth = req.headers.get('authorization') ?? ''
  const match = /^Bearer\s+(.+)$/i.exec(auth)
  if (!match) {
    return NextResponse.json(
      { success: false, error: { code: 'UNAUTHORIZED', message: 'En-tête Authorization: Bearer <clé> requis.' } },
      { status: 401 }
    )
  }
  const rawKey = match[1].trim()
  const keyHash = createHash('sha256').update(rawKey).digest('hex')
  const apiKey = await db.apiKey.findUnique({
    where: { keyHash },
    include: { workspace: true },
  })
  if (!apiKey || apiKey.status !== 'ACTIF') {
    return NextResponse.json(
      { success: false, error: { code: 'INVALID_API_KEY', message: 'Clé API invalide ou révoquée.' } },
      { status: 403 }
    )
  }

  // 2. Parse body
  let body: { events?: IncomingEvent[] }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json(
      { success: false, error: { code: 'INVALID_JSON', message: 'Corps JSON invalide.' } },
      { status: 400 }
    )
  }
  const events = Array.isArray(body.events) ? body.events : []
  if (events.length === 0) {
    return NextResponse.json({ success: true, received: 0, duplicates: 0, errors: [] })
  }
  if (events.length > 1000) {
    return NextResponse.json(
      { success: false, error: { code: 'TOO_MANY_EVENTS', message: 'Maximum 1000 événements par requête.' } },
      { status: 413 }
    )
  }

  // 3. Upsert API key lastUsedAt
  await db.apiKey.update({ where: { id: apiKey.id }, data: { lastUsedAt: new Date() } })

  // 4. Process events — idempotent by (workspaceId, eventId)
  let received = 0
  let duplicates = 0
  const errors: { event_id: string; error: string }[] = []

  // Resolve or create a lightweight Campaign record per unique campaign_name (for grouping)
  const campaignCache = new Map<string, string>() // name → campaignId

  for (const ev of events) {
    if (!ev.event_id || !ev.email || !ev.type) {
      errors.push({ event_id: ev.event_id ?? '(missing)', error: 'Champs requis manquants (event_id, email, type).' })
      continue
    }
    if (!VALID_EVENT_TYPES.has(ev.type)) {
      errors.push({ event_id: ev.event_id, error: `Type "${ev.type}" non supporté. Valides: ${[...VALID_EVENT_TYPES].join(', ')}.` })
      continue
    }
    const occurredAt = ev.occurred_at ? new Date(ev.occurred_at) : new Date()
    if (isNaN(occurredAt.getTime())) {
      errors.push({ event_id: ev.event_id, error: 'occurred_at doit être une date ISO valide.' })
      continue
    }

    // Campaign grouping (optional)
    let campaignId: string | null = null
    if (ev.campaign_name) {
      const name = ev.campaign_name.slice(0, 200)
      if (campaignCache.has(name)) {
        campaignId = campaignCache.get(name)!
      } else {
        // Find or create a lightweight campaign record (just for event grouping)
        let campaign = await db.campaign.findFirst({
          where: { workspaceId: apiKey.workspaceId, name },
          orderBy: { createdAt: 'desc' },
        })
        if (!campaign) {
          campaign = await db.campaign.create({
            data: {
              workspaceId: apiKey.workspaceId,
              name,
              subject: '',
              status: 'ENVOYEE',
              sentAt: occurredAt,
            },
          })
        }
        campaignId = campaign.id
        campaignCache.set(name, campaignId)
      }
    } else if (ev.campaign_id) {
      // Verify the campaign_id belongs to this workspace
      const c = await db.campaign.findFirst({
        where: { id: ev.campaign_id, workspaceId: apiKey.workspaceId },
        select: { id: true },
      })
      if (c) campaignId = c.id
    }

    // Idempotent insert — UNIQUE(workspace_id, event_id) constraint
    try {
      await db.emailEvent.create({
        data: {
          workspaceId: apiKey.workspaceId,
          campaignId,
          contactEmail: ev.email.toLowerCase().slice(0, 320),
          eventId: ev.event_id.slice(0, 200),
          eventType: ev.type,
          occurredAt,
          messageId: ev.event_id.slice(0, 200),
        },
      })
      received++
    } catch (e: any) {
      // Prisma throws P2002 on unique constraint violation → duplicate
      if (e?.code === 'P2002') {
        duplicates++
      } else {
        errors.push({ event_id: ev.event_id, error: 'Erreur DB: ' + (e?.message ?? 'unknown') })
      }
    }
  }

  // 5. Update campaign recipientCount + sentAt (best-effort)
  for (const [name, cid] of campaignCache.entries()) {
    try {
      const count = await db.emailEvent.count({
        where: { campaignId: cid, eventType: 'SENT' },
      })
      await db.campaign.update({
        where: { id: cid },
        data: { recipientCount: count },
      })
    } catch {}
  }

  return NextResponse.json({
    success: true,
    received,
    duplicates,
    errors,
  })
}

/**
 * GET /api/v1/events — health check (no auth required).
 * Returns the supported event types + endpoint documentation.
 */
export async function GET() {
  return NextResponse.json({
    success: true,
    endpoint: 'POST /api/v1/events',
    description: 'Ingestion d’événements e-mail pour le reporting EmailOqui.',
    auth: 'Bearer <api_key>',
    supported_types: [...VALID_EVENT_TYPES],
    max_events_per_request: 1000,
    example: {
      events: [
        {
          event_id: 'evt_123',
          email: 'recipient@example.com',
          type: 'SENT',
          campaign_name: 'Newsletter Octobre',
          occurred_at: '2026-10-15T10:30:00Z',
        },
      ],
    },
  })
}
